import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const t = (arr: string[]) => JSON.stringify(arr);

async function main() {
  console.log("Iniciando seed...");

  await prisma.promptCopy.deleteMany();
  await prisma.review.deleteMany();
  await prisma.purchase.deleteMany();
  await prisma.favorite.deleteMany();
  await prisma.subscription.deleteMany();
  await prisma.prompt.deleteMany();
  await prisma.category.deleteMany();
  await prisma.creatorProfile.deleteMany();
  await prisma.session.deleteMany();
  await prisma.account.deleteMany();
  await prisma.user.deleteMany();

  const categories = await Promise.all([
    prisma.category.create({ data: { name: "Videos Virais",     slug: "videos-virais",    icon: "video",  description: "Prompts para criar videos que viralizam nas redes sociais" } }),
    prisma.category.create({ data: { name: "Imagens Realistas", slug: "imagens-realistas", icon: "camera", description: "Prompts para imagens hiper-realistas com IA" } }),
    prisma.category.create({ data: { name: "Anime e Games",     slug: "anime-games",      icon: "game",   description: "Prompts no estilo anime, manga e jogos" } }),
    prisma.category.create({ data: { name: "Negocios",          slug: "negocios",         icon: "brief",  description: "Prompts para apresentacoes, logos e marketing" } }),
    prisma.category.create({ data: { name: "Social Media",      slug: "social-media",     icon: "phone",  description: "Prompts para posts e conteudo de redes sociais" } }),
    prisma.category.create({ data: { name: "E-commerce",        slug: "e-commerce",       icon: "cart",   description: "Prompts para fotos de produto e banners de loja" } }),
    prisma.category.create({ data: { name: "YouTube",           slug: "youtube",          icon: "play",   description: "Thumbnails, miniaturas e arte para canal YouTube" } }),
    prisma.category.create({ data: { name: "TikTok e Reels",   slug: "tiktok-reels",     icon: "music",  description: "Prompts para videos curtos e virais" } }),
    prisma.category.create({ data: { name: "Prompts Gratis",   slug: "prompts-gratis",   icon: "gift",   description: "Colecao gratuita para comecar a criar" } }),
    prisma.category.create({ data: { name: "Packs Premium",    slug: "packs-premium",    icon: "box",    description: "Pacotes completos com multiplos prompts tematicos" } }),
  ]);

  const [vidVirais, imgReal, animeGames, negocios, socialMedia, ecommerce, youtube, tiktok, , packs] = categories;

  const hashedPassword = await bcrypt.hash("senha123", 12);

  const admin = await prisma.user.create({
    data: { name: "Admin PromptHub", email: "admin@prompthub.com.br", password: hashedPassword, role: "ADMIN", plan: "CREATOR" },
  });

  const creator1 = await prisma.user.create({
    data: { name: "Lucas Vieira", email: "lucas@prompthub.com.br", password: hashedPassword, role: "CREATOR", plan: "CREATOR", image: "https://i.pravatar.cc/150?img=12" },
  });

  const creator2 = await prisma.user.create({
    data: { name: "Ana Rodrigues", email: "ana@prompthub.com.br", password: hashedPassword, role: "CREATOR", plan: "CREATOR", image: "https://i.pravatar.cc/150?img=47" },
  });

  const creator3 = await prisma.user.create({
    data: { name: "Rafael Costa", email: "rafael@prompthub.com.br", password: hashedPassword, role: "CREATOR", plan: "PRO", image: "https://i.pravatar.cc/150?img=33" },
  });

  const userComum = await prisma.user.create({
    data: { name: "Maria Teste", email: "usuario@prompthub.com.br", password: hashedPassword, role: "USER", plan: "FREE" },
  });

  await prisma.creatorProfile.createMany({
    data: [
      { userId: creator1.id, bio: "Especialista em prompts para videos virais.", totalPrompts: 18, totalSales: 342, rating: 4.9 },
      { userId: creator2.id, bio: "Designer e criadora de prompts para imagens realistas.", totalPrompts: 15, totalSales: 289, rating: 4.8 },
      { userId: creator3.id, bio: "Dev entusiasta de IA generativa. Foco em textos e negocios.", totalPrompts: 12, totalSales: 198, rating: 4.7 },
    ],
  });

  const prompts = [
    // ── IMAGENS ──
    { title: "Retrato Cinematografico Realista", slug: "retrato-cinematografico-realista", description: "Retratos com iluminacao cinematografica, qualidade editorial.", type: "IMAGE", categoryId: imgReal.id, creatorId: creator2.id, promptPt: "Retrato fotografico ultrarrealista de uma mulher, iluminacao cinematografica de tres pontos, bokeh suave ao fundo, olhos expressivos com reflexo de luz, textura de pele realista, qualidade editorial Vogue, camera Canon EOS R5, lente 85mm f/1.4, tons quentes dourados", promptEn: "Ultra-realistic portrait photography of a woman, cinematic three-point lighting, soft background bokeh, expressive eyes with light reflections, realistic skin texture, Vogue editorial quality, Canon EOS R5 camera, 85mm f/1.4 lens, warm golden tones", negativePrompt: "cartoon, anime, low quality, blurry, distorted, extra fingers", instructions: "Use no Midjourney com --ar 4:5 --v 6.1. Substitua mulher por qualquer pessoa.", recommendedTool: "Midjourney", aspectRatio: "4:5", tags: t(["retrato", "realismo", "fotografia", "editorial"]), price: 19.9, isFree: false, isPremium: true, isFeatured: true, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600", copiesCount: 847, favoritesCount: 312, salesCount: 94 },
    { title: "Wallpaper Anime Epico 4K", slug: "wallpaper-anime-epico-4k", description: "Cenas epicas no estilo anime com detalhes cinematograficos.", type: "IMAGE", categoryId: animeGames.id, creatorId: creator2.id, promptPt: "Cena epica anime estilo Studio Ghibli e Makoto Shinkai, personagem em pe no topo de uma montanha ao por do sol, nuvens dramaticas coloridas em laranja e roxo, particulas de luz dourada, arte em 4K ultra detalhada, composicao cinematografica", promptEn: "Epic anime scene Studio Ghibli and Makoto Shinkai style, character standing on top of a mountain at sunset, dramatic orange and purple clouds, golden light particles, 4K ultra detailed art, cinematic composition", negativePrompt: "low quality, western style, realistic photography", instructions: "Melhor no Midjourney v6 com --ar 16:9 --style raw", recommendedTool: "Midjourney", aspectRatio: "16:9", tags: t(["anime", "wallpaper", "4k", "ghibli"]), price: 14.9, isFree: false, isPremium: true, isFeatured: true, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600", copiesCount: 1243, favoritesCount: 567, salesCount: 156 },
    { title: "Foto de Produto Premium", slug: "foto-produto-premium", description: "Fotos de produto com qualidade de catalogo profissional.", type: "IMAGE", categoryId: ecommerce.id, creatorId: creator1.id, promptPt: "Fotografia de produto profissional, fundo branco limpo, iluminacao de estudio perfeita, sombra suave, produto centralizado, reflexo elegante no fundo, qualidade e-commerce Amazon", promptEn: "Professional product photography, clean white background, perfect studio lighting, soft shadow, centered product, elegant reflection on background, Amazon e-commerce quality", negativePrompt: "people, hands, cluttered background, low quality", instructions: "Substitua produto pela descricao do seu item. Use ChatGPT Image para variacoes.", recommendedTool: "ChatGPT Image", aspectRatio: "1:1", tags: t(["produto", "ecommerce", "fotografia", "loja"]), price: 0, isFree: true, isPremium: false, isFeatured: true, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600", copiesCount: 3421, favoritesCount: 892, salesCount: 0 },
    { title: "Logo Minimalista Moderno", slug: "logo-minimalista-moderno", description: "Logos minimalistas para marcas digitais.", type: "IMAGE", categoryId: negocios.id, creatorId: creator2.id, promptPt: "Logo minimalista e moderno para empresa de tecnologia, fundo preto, icone abstrato em roxo e branco, tipografia sans-serif limpa, design premium, estilo Apple, formato vetorial, proporcoes perfeitas", promptEn: "Minimalist modern logo for tech company, black background, abstract icon in purple and white, clean sans-serif typography, premium design, Apple style, vector format", negativePrompt: "complex, cluttered, vintage, 3D effects", instructions: "Ideal para Midjourney. Adicione o nome da empresa no prompt.", recommendedTool: "Midjourney", aspectRatio: "1:1", tags: t(["logo", "marca", "minimalista", "negocio"]), price: 24.9, isFree: false, isPremium: true, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600", copiesCount: 678, favoritesCount: 234, salesCount: 67 },
    { title: "Imagem de Perfil Profissional IA", slug: "imagem-perfil-profissional-ia", description: "Transforme qualquer foto em imagem de perfil profissional.", type: "IMAGE", categoryId: socialMedia.id, creatorId: creator2.id, promptPt: "Foto de perfil profissional LinkedIn, pessoa sorridente confiante, fundo desfocado em azul ou cinza, iluminacao natural suave, terno ou roupa profissional, qualidade fotografica alta, expressao amigavel", promptEn: "Professional LinkedIn profile photo, confident smiling person, blurred blue or gray background, soft natural lighting, professional clothing, high photographic quality, friendly expression", negativePrompt: "casual clothes, bad lighting, low quality, filters", instructions: "Use com Gemini ou ChatGPT Image. Descreva as caracteristicas da pessoa.", recommendedTool: "Gemini", aspectRatio: "1:1", tags: t(["perfil", "linkedin", "profissional", "foto"]), price: 0, isFree: true, isPremium: false, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600", copiesCount: 2156, favoritesCount: 734, salesCount: 0 },
    { title: "Thumbnail YouTube Impactante", slug: "thumbnail-youtube-impactante", description: "Thumbnails com alto CTR para YouTube.", type: "IMAGE", categoryId: youtube.id, creatorId: creator1.id, promptPt: "Thumbnail YouTube profissional, fundo colorido impactante, texto grande e legivel, pessoa com expressao de surpresa, elementos de design modernos, contraste alto, cores vibrantes laranja e preto, seta chamativa", promptEn: "Professional YouTube thumbnail, impactful colored background, large readable text, person with surprised expression, modern design elements, high contrast, vibrant orange and black colors", negativePrompt: "boring, plain, small text, low contrast", instructions: "Dimensao ideal: 1280x720px. Use o ChatGPT Image para adicionar texto.", recommendedTool: "ChatGPT Image", aspectRatio: "16:9", tags: t(["thumbnail", "youtube", "ctr", "design"]), price: 19.9, isFree: false, isPremium: true, isFeatured: true, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1611162616305-c69b3710bc02?w=600", copiesCount: 1876, favoritesCount: 643, salesCount: 112 },
    { title: "Arte Futurista Cyberpunk", slug: "arte-futurista-cyberpunk", description: "Paisagens e personagens cyberpunk com detalhes incriveis.", type: "IMAGE", categoryId: animeGames.id, creatorId: creator3.id, promptPt: "Arte cyberpunk futurista, cidade noturna com luzes neon azuis e rosas, chuva, personagem com roupas tecnologicas, reflexos no chao molhado, hologramas flutuantes, detalhes ultra-nitidos, estilo Blade Runner 2049", promptEn: "Futuristic cyberpunk art, nighttime city with blue and pink neon lights, rain, character with tech clothing, reflections on wet floor, floating holograms, ultra-sharp details, Blade Runner 2049 style", negativePrompt: "day, nature, low detail, cartoon", instructions: "Use no Midjourney com --ar 16:9 --v 6.1 --q 2", recommendedTool: "Midjourney", aspectRatio: "16:9", tags: t(["cyberpunk", "neon", "futurismo", "wallpaper"]), price: 17.9, isFree: false, isPremium: true, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600", copiesCount: 934, favoritesCount: 445, salesCount: 78 },
    { title: "Post Instagram Aesthetic", slug: "post-instagram-aesthetic", description: "Posts minimalistas e aesthetics para o feed do Instagram.", type: "IMAGE", categoryId: socialMedia.id, creatorId: creator2.id, promptPt: "Post Instagram aesthetic minimalista, paleta de cores neutras (bege, branco, creme), produto no centro, sombra suave lateral, composicao clean, fundo de madeira clara ou marmore branco", promptEn: "Minimalist aesthetic Instagram post, neutral color palette (beige, white, cream), centered product, soft side shadow, clean composition, light wood or white marble background", negativePrompt: "busy background, too many objects, neon colors", instructions: "Formato quadrado 1:1. Troque o objeto pela descricao do seu produto.", recommendedTool: "ChatGPT Image", aspectRatio: "1:1", tags: t(["instagram", "aesthetic", "feed", "minimalista"]), price: 0, isFree: true, isPremium: false, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600", copiesCount: 4234, favoritesCount: 1123, salesCount: 0 },
    { title: "Anuncio de Produto Realista", slug: "anuncio-produto-realista", description: "Anuncios publicitarios de produto com qualidade de agencia.", type: "IMAGE", categoryId: ecommerce.id, creatorId: creator1.id, promptPt: "Anuncio publicitario profissional de produto, composicao dinamica, produto em destaque com iluminacao dramatica, fundo gradiente escuro, texto de call-to-action, qualidade de campanha de marketing premium, fotorrealismo", promptEn: "Professional product advertisement, dynamic composition, product with dramatic lighting, dark gradient background, call-to-action text, premium marketing campaign quality, photorealism", negativePrompt: "low quality, amateur, cluttered", instructions: "Descreva seu produto. Funciona muito bem com ChatGPT Image e Gemini.", recommendedTool: "Gemini", aspectRatio: "16:9", tags: t(["anuncio", "marketing", "produto", "publicidade"]), price: 29.9, isFree: false, isPremium: true, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600", copiesCount: 567, favoritesCount: 198, salesCount: 45 },
    { title: "Paisagem Fantasia Epica", slug: "paisagem-fantasia-epica", description: "Paisagens de mundos fantasticos com qualidade cinematografica.", type: "IMAGE", categoryId: animeGames.id, creatorId: creator3.id, promptPt: "Paisagem de fantasia epica, castelo flutuante nas nuvens ao amanhecer, cascata de cristal, floresta magica com arvores luminosas, raios de luz dourada, nevoa suave, arte concept cinematografica", promptEn: "Epic fantasy landscape, floating castle in clouds at dawn, crystal waterfall, magical forest with glowing trees, golden light rays, soft mist, cinematic concept art", negativePrompt: "modern, urban, realistic photography", instructions: "Melhor com Midjourney v6. Use --ar 16:9 para wallpaper.", recommendedTool: "Midjourney", aspectRatio: "16:9", tags: t(["fantasia", "paisagem", "castelo", "magia"]), price: 14.9, isFree: false, isPremium: false, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?w=600", copiesCount: 723, favoritesCount: 289, salesCount: 34 },
    { title: "Foto Casal Romantico", slug: "foto-casal-romantico", description: "Fotos de casal em cenarios romanticos.", type: "IMAGE", categoryId: imgReal.id, creatorId: creator2.id, promptPt: "Foto de casal romantica ao por do sol, silhuetas contra o ceu colorido, tons quentes dourados e laranja, foco suave, qualidade fotografica profissional", promptEn: "Romantic couple photo at sunset, silhouettes against colorful sky, warm golden and orange tones, soft focus, professional photography quality", negativePrompt: "indoor, artificial light, ugly", instructions: "Funciona com Gemini e ChatGPT Image. Adicione a etnia ou caracteristicas do casal.", recommendedTool: "Gemini", aspectRatio: "4:5", tags: t(["casal", "romantico", "foto", "sunset"]), price: 0, isFree: true, isPremium: false, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1516589091380-5d8e87df6999?w=600", copiesCount: 1897, favoritesCount: 654, salesCount: 0 },
    { title: "Arte de Personagem RPG", slug: "arte-personagem-rpg", description: "Criacao de personagens de RPG com design detalhado.", type: "IMAGE", categoryId: animeGames.id, creatorId: creator3.id, promptPt: "Arte de personagem RPG, guerreiro elfico com armadura prateada ornamentada, cabelo longo prateado, olhos azuis brilhantes, fundo epico de batalha ao amanhecer, qualidade de ilustracao de capa de livro", promptEn: "RPG character art, elven warrior with ornate silver armor, long silver hair, bright blue eyes, epic dawn battle background, book cover illustration quality", negativePrompt: "low detail, cartoon, chibi", instructions: "Personalize com a raca, classe e estilo do seu personagem.", recommendedTool: "Midjourney", aspectRatio: "2:3", tags: t(["rpg", "personagem", "guerreiro", "fantasia"]), price: 19.9, isFree: false, isPremium: true, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1551645120-d70bfe84c826?w=600", copiesCount: 445, favoritesCount: 178, salesCount: 28 },
    // ── VIDEOS ──
    { title: "Video POV Cinematografico para Reels", slug: "video-pov-cinematografico-reels", description: "Video em perspectiva POV com qualidade cinematografica.", type: "VIDEO", categoryId: tiktok.id, creatorId: creator1.id, promptPt: "Video POV cinematografico caminhando em uma rua de Paris ao entardecer, camera na altura dos olhos, movimento suave de steadicam, luzes da cidade ao fundo desfocadas, aspecto filmico 16mm", promptEn: "Cinematic POV video walking on a Paris street at dusk, eye-level camera, smooth steadicam movement, blurred city lights in background, 16mm film look", negativePrompt: "shaky camera, overexposed, artificial look", instructions: "Use no Sora ou Veo com duracao de 6-10 segundos. Ideal para loop em Reels.", recommendedTool: "Sora", aspectRatio: "9:16", tags: t(["pov", "reels", "tiktok", "cinematografico"]), price: 29.9, isFree: false, isPremium: true, isFeatured: true, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600", copiesCount: 2341, favoritesCount: 876, salesCount: 187 },
    { title: "Transformacao Produto Explosiva", slug: "transformacao-produto-explosiva", description: "Animacao de produto com particulas e efeitos para anuncios.", type: "VIDEO", categoryId: ecommerce.id, creatorId: creator1.id, promptPt: "Video de produto com particulas douradas explodindo ao redor, produto girando em camera lenta, fundo preto premium, reflexo espelhado, particulas de luz dancando, revelacao dramatica", promptEn: "Product video with golden particles exploding around it, product rotating in slow motion, premium black background, mirrored reflection, dancing light particles, dramatic reveal", negativePrompt: "amateur, shaky, low quality", instructions: "Use no Runway ou Kling. Especifique o produto na primeira linha.", recommendedTool: "Runway", aspectRatio: "1:1", tags: t(["produto", "anuncio", "particulas", "comercial"]), price: 34.9, isFree: false, isPremium: true, isFeatured: true, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600", copiesCount: 1234, favoritesCount: 498, salesCount: 143 },
    { title: "Texto Animado Motivacional", slug: "texto-animado-motivacional", description: "Citacoes motivacionais com animacao elegante para Stories.", type: "VIDEO", categoryId: tiktok.id, creatorId: creator3.id, promptPt: "Video com texto motivacional aparecendo com animacao elegante, letras douradas em fundo escuro gradiente, particulas sutis ao fundo, duracao de 15 segundos, formato Stories 9:16", promptEn: "Video with motivational text appearing with elegant animation, golden letters on dark gradient background, subtle particles in background, 15 second duration, 9:16 Stories format", negativePrompt: "cheap, pixelated, ugly font", instructions: "Especifique sua frase no prompt. Use Pika ou Runway.", recommendedTool: "Pika", aspectRatio: "9:16", tags: t(["texto", "motivacional", "stories", "animacao"]), price: 0, isFree: true, isPremium: false, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600", copiesCount: 5678, favoritesCount: 2134, salesCount: 0 },
    { title: "Intro YouTube Profissional", slug: "intro-youtube-profissional", description: "Intro de canal YouTube com logo animado e efeitos premium.", type: "VIDEO", categoryId: youtube.id, creatorId: creator1.id, promptPt: "Intro profissional de canal YouTube com 5 segundos, logo com efeito de particulas e explosao de luz, fundo escuro com grade de luz neon, textura de metal cromado", promptEn: "Professional YouTube channel intro 5 seconds long, logo with particle effect and light explosion, dark background with neon light grid, chrome metal texture", negativePrompt: "amateur, long, boring, slow", instructions: "Substitua logo pela descricao do simbolo do seu canal. Use Runway ou Kling.", recommendedTool: "Kling", aspectRatio: "16:9", tags: t(["intro", "youtube", "logo", "animacao"]), price: 39.9, isFree: false, isPremium: true, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1611162616305-c69b3710bc02?w=600", copiesCount: 876, favoritesCount: 345, salesCount: 67 },
    { title: "Video Viral Satisfatorio", slug: "video-viral-satisfatorio", description: "Loops satisfatorios com alto potencial viral.", type: "VIDEO", categoryId: tiktok.id, creatorId: creator1.id, promptPt: "Video satisfatorio de areia colorida sendo despejada em padroes geometricos, cores vibrantes e contrastantes, loop perfeito de 3 segundos, close-up extremo, iluminacao uniforme", promptEn: "Satisfying video of colored sand being poured in geometric patterns, vibrant contrasting colors, perfect 3-second loop, extreme close-up, uniform lighting", negativePrompt: "boring, slow, dull colors", instructions: "Use no Veo ou Sora. Troque areia colorida por qualquer material satisfatorio.", recommendedTool: "Veo", aspectRatio: "9:16", tags: t(["satisfatorio", "tiktok", "viral", "loop"]), price: 0, isFree: true, isPremium: false, isFeatured: true, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600", copiesCount: 7823, favoritesCount: 3456, salesCount: 0 },
    { title: "Abertura de Pacote Hype", slug: "abertura-pacote-hype", description: "Video de unboxing dramatico para conteudo de produto.", type: "VIDEO", categoryId: vidVirais.id, creatorId: creator1.id, promptPt: "Video de unboxing dramatico, maos abrindo caixa premium com luz saindo de dentro, efeito de particulas douradas explodindo ao abrir, camera lenta, fundo escuro", promptEn: "Dramatic unboxing video, hands opening premium box with light coming from inside, golden particle effect on opening, slow motion, dark background", negativePrompt: "amateur, shaky, low quality, cheap", instructions: "Descreva sua caixa de produto. Funciona com Runway Gen-3.", recommendedTool: "Runway", aspectRatio: "9:16", tags: t(["unboxing", "produto", "hype", "reels"]), price: 29.9, isFree: false, isPremium: true, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600", copiesCount: 987, favoritesCount: 412, salesCount: 78 },
    { title: "Transicao de Roupa Viral", slug: "transicao-roupa-viral", description: "Transicao de troca de roupa viral para TikTok.", type: "VIDEO", categoryId: tiktok.id, creatorId: creator2.id, promptPt: "Video de transicao de moda, pessoa em roupas casuais pisca e aparece com look glamouroso, efeito de particulas e flash de luz, camera estatica, cenario clean e moderno", promptEn: "Fashion transition video, person in casual clothes blinks and appears in glamorous look, particle effect and light flash, static camera, clean modern setting", negativePrompt: "abrupt cut, amateur, shaky", instructions: "Especifique os looks no prompt. Viral com Runway e Pika.", recommendedTool: "Pika", aspectRatio: "9:16", tags: t(["transicao", "moda", "viral", "tiktok"]), price: 0, isFree: true, isPremium: false, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600", copiesCount: 6543, favoritesCount: 2876, salesCount: 0 },
    { title: "Slow Motion Chuva Urbana", slug: "slow-motion-chuva-urbana", description: "Cenas de chuva em camera lenta com estetica cinematografica.", type: "VIDEO", categoryId: vidVirais.id, creatorId: creator3.id, promptPt: "Super camera lenta de chuva em rua urbana noturna, gotas iluminadas pelos postes de luz laranja, reflexo na calcada molhada, 120fps slow motion, grao de filme analogico", promptEn: "Super slow motion rain on nighttime urban street, raindrops lit by orange streetlights, reflection on wet pavement, 120fps slow motion, analog film grain", negativePrompt: "sunny, bright, cheap", instructions: "Funciona com Veo e Sora. Use para backgrounds de videos virais.", recommendedTool: "Veo", aspectRatio: "9:16", tags: t(["chuva", "slow motion", "cinematografico", "urbano"]), price: 19.9, isFree: false, isPremium: false, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1519692933481-e162a57d6721?w=600", copiesCount: 789, favoritesCount: 312, salesCount: 45 },
    // ── TEXTOS ──
    { title: "Bio Instagram Irresistivel", slug: "bio-instagram-irresistivel", description: "Bios para Instagram que convertem visitantes em seguidores.", type: "TEXT", categoryId: socialMedia.id, creatorId: creator3.id, promptPt: "Crie uma bio para Instagram de [descreva seu perfil] que seja impactante, use emojis relevantes, contenha proposta de valor clara, CTA para o link na bio, maximo de 150 caracteres", instructions: "Substitua os colchetes pelas suas informacoes. Funciona com ChatGPT e Gemini.", recommendedTool: "ChatGPT", tags: t(["bio", "instagram", "copywriting"]), price: 0, isFree: true, isPremium: false, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=600", copiesCount: 8934, favoritesCount: 3456, salesCount: 0 },
    { title: "Script de Video Viral", slug: "script-video-viral", description: "Roteiros para videos curtos com estrutura de viralizacao.", type: "TEXT", categoryId: tiktok.id, creatorId: creator3.id, promptPt: "Crie um script de video TikTok/Reels de 60 segundos sobre [tema], com gancho impactante nos primeiros 3 segundos, storytelling envolvente no meio, CTA claro no final. Tom: [serio/divertido]. Publico: [descreva]", instructions: "Preencha os colchetes. O gancho dos 3 primeiros segundos e fundamental.", recommendedTool: "ChatGPT", tags: t(["script", "tiktok", "viral", "copywriting"]), price: 19.9, isFree: false, isPremium: true, isFeatured: true, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600", copiesCount: 3456, favoritesCount: 1234, salesCount: 234 },
    { title: "Descricao de Produto que Vende", slug: "descricao-produto-que-vende", description: "Textos de produto persuasivos focados em conversao.", type: "TEXT", categoryId: ecommerce.id, creatorId: creator3.id, promptPt: "Escreva uma descricao de produto persuasiva para [nome do produto], use gatilhos mentais de urgencia, escassez e prova social. Inclua caracteristicas tecnicas, beneficios emocionais e CTA forte. Publico: [descreva]. Maximo 200 palavras.", instructions: "Complete os colchetes. Funciona para marketplaces, e-commerce e landing pages.", recommendedTool: "ChatGPT", tags: t(["produto", "ecommerce", "copywriting", "vendas"]), price: 14.9, isFree: false, isPremium: false, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600", copiesCount: 2345, favoritesCount: 876, salesCount: 167 },
    { title: "Email Marketing de Alta Conversao", slug: "email-marketing-alta-conversao", description: "Sequencia de emails com alta taxa de abertura.", type: "TEXT", categoryId: negocios.id, creatorId: creator3.id, promptPt: "Crie um email marketing para [produto] com: assunto com alta taxa de abertura, abertura personalizada, storytelling de 2 paragrafos, prova social, oferta clara e CTA duplo. Empresa: [nome]", instructions: "Preencha todos os campos entre colchetes.", recommendedTool: "ChatGPT", tags: t(["email", "marketing", "conversao", "copywriting"]), price: 24.9, isFree: false, isPremium: true, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=600", copiesCount: 1234, favoritesCount: 567, salesCount: 89 },
    { title: "Legenda Engajamento Instagram", slug: "legenda-engajamento-instagram", description: "Legendas que maximizam comentarios e compartilhamentos.", type: "TEXT", categoryId: socialMedia.id, creatorId: creator2.id, promptPt: "Escreva uma legenda engajante para Instagram sobre [tema], inclua gancho na primeira linha, 2-3 paragrafos de valor, pergunta no final para comentarios, 5 hashtags relevantes. Nicho: [seu nicho]", instructions: "Ajuste o tema e nicho. Ideal para contas de conteudo e negocios.", recommendedTool: "ChatGPT", tags: t(["instagram", "legenda", "engajamento", "hashtag"]), price: 0, isFree: true, isPremium: false, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=600", copiesCount: 6789, favoritesCount: 2345, salesCount: 0 },
    { title: "Calendario de Conteudo 30 Dias", slug: "calendario-conteudo-30-dias", description: "Planejamento completo de conteudo para um mes.", type: "TEXT", categoryId: socialMedia.id, creatorId: creator2.id, promptPt: "Crie um calendario de conteudo para redes sociais para 30 dias para [tipo de negocio], distribuindo: 40% educativo, 30% entretenimento, 20% vendas, 10% bastidores. Inclua temas, formatos, dias e horarios. Plataformas: [Instagram/TikTok]", instructions: "Adapte as porcentagens ao seu objetivo.", recommendedTool: "ChatGPT", tags: t(["calendario", "conteudo", "planejamento", "estrategia"]), price: 34.9, isFree: false, isPremium: true, isFeatured: true, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=600", copiesCount: 4567, favoritesCount: 1876, salesCount: 312 },
    // ── PACKS ──
    { title: "Pack Criador de Conteudo Pro", slug: "pack-criador-conteudo-pro", description: "Pack completo com 15 prompts para criadores de conteudo digital.", type: "PACK", categoryId: packs.id, creatorId: creator1.id, promptPt: "PACK com 15 prompts: 5 scripts de videos virais, 3 prompts de imagem para thumbnails e capas, 4 legendas de alto engajamento, 3 roteiros de YouTube Shorts.", instructions: "Este pack inclui acesso a todos os 15 prompts na area de downloads.", recommendedTool: "ChatGPT, Midjourney, Sora", aspectRatio: "1:1", tags: t(["pack", "criador", "conteudo", "completo"]), price: 79.9, isFree: false, isPremium: true, isFeatured: true, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1611162616305-c69b3710bc02?w=600", copiesCount: 567, favoritesCount: 234, salesCount: 89 },
    { title: "Pack E-commerce Total", slug: "pack-ecommerce-total", description: "12 prompts para lojas virtuais. Fotos, anuncios, descricoes e banners.", type: "PACK", categoryId: packs.id, creatorId: creator2.id, promptPt: "PACK com 12 prompts: 4 prompts de foto de produto, 3 prompts de anuncio para Meta Ads, 3 descricoes de produto, 2 prompts de banner.", instructions: "Ideal para donos de loja virtual, dropshippers e gestores de e-commerce.", recommendedTool: "ChatGPT Image, Midjourney", aspectRatio: "1:1", tags: t(["pack", "ecommerce", "produto", "anuncio"]), price: 89.9, isFree: false, isPremium: true, isFeatured: true, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600", copiesCount: 345, favoritesCount: 178, salesCount: 67 },
    { title: "Pack Videos Virais TikTok", slug: "pack-videos-virais-tiktok", description: "10 prompts de video testados com mais de 1M views combinados.", type: "PACK", categoryId: packs.id, creatorId: creator1.id, promptPt: "PACK com 10 prompts de video viral: 3 POVs cinematograficos, 2 transicoes de roupa, 2 videos satisfatorios, 2 timelapses dramaticos, 1 mega pack de hooks.", instructions: "Todos os prompts foram testados e geraram pelo menos 500K views.", recommendedTool: "Sora, Veo, Runway", aspectRatio: "9:16", tags: t(["pack", "tiktok", "viral", "video"]), price: 99.9, isFree: false, isPremium: true, isFeatured: true, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600", copiesCount: 678, favoritesCount: 289, salesCount: 112 },
    { title: "Pack Anime e Arte Digital", slug: "pack-anime-arte-digital", description: "8 prompts para criar artes no estilo anime, manga e game art.", type: "PACK", categoryId: packs.id, creatorId: creator3.id, promptPt: "PACK com 8 prompts: 3 wallpapers anime epicos, 2 artes de personagem RPG, 2 cenas de manga cinematografico, 1 arte chibi kawaii.", instructions: "Inclui guia de configuracoes de estilo para Midjourney.", recommendedTool: "Midjourney", aspectRatio: "1:1", tags: t(["pack", "anime", "arte", "midjourney"]), price: 59.9, isFree: false, isPremium: true, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600", copiesCount: 432, favoritesCount: 189, salesCount: 45 },
    { title: "Pack Negocios e Marketing", slug: "pack-negocios-marketing", description: "20 prompts de texto para negocios: pitches, emails e apresentacoes.", type: "PACK", categoryId: packs.id, creatorId: creator3.id, promptPt: "PACK com 20 prompts: 5 pitches de vendas, 5 emails marketing, 4 scripts para reuniao, 3 apresentacoes de empresa, 3 propostas comerciais.", instructions: "Cada prompt vem com instrucoes de preenchimento e exemplo de resultado.", recommendedTool: "ChatGPT, Gemini", tags: t(["pack", "negocios", "marketing", "texto"]), price: 119.9, isFree: false, isPremium: true, isFeatured: false, status: "APPROVED", previewImage: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600", copiesCount: 234, favoritesCount: 123, salesCount: 34 },
  ];

  for (const p of prompts) {
    await prisma.prompt.create({ data: p as any });
  }

  const allPrompts = await prisma.prompt.findMany({ take: 6 });
  for (const prompt of allPrompts) {
    await prisma.review.create({
      data: { userId: userComum.id, promptId: prompt.id, rating: 5, comment: "Prompt excelente! Resultado incrivel logo na primeira tentativa." },
    });
  }

  console.log(`Seed concluido: ${categories.length} categorias, 5 usuarios, ${prompts.length} prompts`);
  void admin;
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
